
service: aijaz-practice-kinesis

provider:
  name: aws
  runtime: nodejs12.x
  role: arn:aws:iam::611740472157:role/Aijaz_sahab

functions:
  addTodo:
    handler: handler.addTodo
    memorySize: 512
    events:
      - http: 
          path: api/aijaz-todo
          method: POST
          cors: true
